INSERT INTO EMPLOYEE (ID, NAME, DEPARTMENT) VALUES (1, 'Rahul', 'Engineering');
INSERT INTO EMPLOYEE (ID, NAME, DEPARTMENT) VALUES (2, 'Ritesh', 'Marketing');
INSERT INTO EMPLOYEE (ID, NAME, DEPARTMENT) VALUES (3, 'Adam', 'IT');
INSERT INTO EMPLOYEE (ID, NAME, DEPARTMENT) VALUES (4, 'John', 'HR');
INSERT INTO EMPLOYEE (ID, NAME, DEPARTMENT) VALUES (5, 'James', 'Sales');